/**
 *
 *  RestfulScorerQuestionCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulScorerQuestionCtrl.h"
#include <string>


void RestfulScorerQuestionCtrl::getOne(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback,
                                       ScorerQuestion::PrimaryKeyType &&id)
{
    RestfulScorerQuestionCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulScorerQuestionCtrl::updateOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          ScorerQuestion::PrimaryKeyType &&id)
{
    RestfulScorerQuestionCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulScorerQuestionCtrl::deleteOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          ScorerQuestion::PrimaryKeyType &&id)
{
    RestfulScorerQuestionCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulScorerQuestionCtrl::get(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulScorerQuestionCtrlBase::get(req, std::move(callback));
}

void RestfulScorerQuestionCtrl::create(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulScorerQuestionCtrlBase::create(req, std::move(callback));
}
