/**
 *
 *  RestfulQuestionsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulQuestionsCtrlBase.h"

#include "Questions.h"
using namespace drogon;
using namespace drogon_model::task;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the questions table.
 */

class RestfulQuestionsCtrl: public drogon::HttpController<RestfulQuestionsCtrl>, public RestfulQuestionsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulQuestionsCtrl::getOne,"/api/control/questions/{1}",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulQuestionsCtrl::updateOne,"/api/control/questions/{1}",Put,Options,"user::authorize");
    ADD_METHOD_TO(RestfulQuestionsCtrl::deleteOne,"/api/control/questions/{1}",Delete,Options,"user::authorize");
    ADD_METHOD_TO(RestfulQuestionsCtrl::get,"/api/control/questions",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulQuestionsCtrl::create,"/api/control/questions",Post,Options,"user::authorize");
    //ADD_METHOD_TO(RestfulQuestionsCtrl::update,"/api/control/questions",Put,Options,"user::authorize");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Questions::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Questions::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Questions::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
