/**
 *
 *  RestfulUserPageCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulUserPageCtrlBase.h"

#include "UserPage.h"
using namespace drogon;
using namespace drogon_model::task;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the user_page table.
 */

class RestfulUserPageCtrl: public drogon::HttpController<RestfulUserPageCtrl>, public RestfulUserPageCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulUserPageCtrl::getOne,"/api/control/userpage/{1}",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulUserPageCtrl::updateOne,"/api/control/userpage/{1}",Put,Options,"user::authorize");
    ADD_METHOD_TO(RestfulUserPageCtrl::deleteOne,"/api/control/userpage/{1}",Delete,Options,"user::authorize");
    ADD_METHOD_TO(RestfulUserPageCtrl::get,"/api/control/userpage",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulUserPageCtrl::create,"/api/control/userpage",Post,Options,"user::authorize");
    //ADD_METHOD_TO(RestfulUserPageCtrl::update,"/api/control/userpage",Put,Options,"user::authorize");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                UserPage::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   UserPage::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   UserPage::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
