/**
 *
 *  RestfulUsersCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulUsersCtrlBase.h"

#include "Users.h"
using namespace drogon;
using namespace drogon_model::task;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the users table.
 */

class RestfulUsersCtrl: public drogon::HttpController<RestfulUsersCtrl>, public RestfulUsersCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulUsersCtrl::getOne,"/api/control/users/{1}",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulUsersCtrl::updateOne,"/api/control/users/{1}",Put,Options,"user::authorize");
    ADD_METHOD_TO(RestfulUsersCtrl::deleteOne,"/api/control/users/{1}",Delete,Options,"user::authorize");
    ADD_METHOD_TO(RestfulUsersCtrl::get,"/api/control/users",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulUsersCtrl::create,"/api/control/users",Post,Options,"user::authorize");
    //ADD_METHOD_TO(RestfulUsersCtrl::update,"/api/control/users",Put,Options,"user::authorize");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Users::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Users::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Users::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
