/**
 *
 *  RestfulPagesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulPagesCtrl.h"
#include <string>


void RestfulPagesCtrl::getOne(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback,
                              Pages::PrimaryKeyType &&id)
{
    RestfulPagesCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulPagesCtrl::updateOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Pages::PrimaryKeyType &&id)
{
    RestfulPagesCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulPagesCtrl::deleteOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Pages::PrimaryKeyType &&id)
{
    RestfulPagesCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulPagesCtrl::get(const HttpRequestPtr &req,
                           std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulPagesCtrlBase::get(req, std::move(callback));
}

void RestfulPagesCtrl::create(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulPagesCtrlBase::create(req, std::move(callback));
}
