/**
 *
 *  RestfulUserPageCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulUserPageCtrl.h"
#include <string>


void RestfulUserPageCtrl::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 UserPage::PrimaryKeyType &&id)
{
    RestfulUserPageCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulUserPageCtrl::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    UserPage::PrimaryKeyType &&id)
{
    RestfulUserPageCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulUserPageCtrl::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    UserPage::PrimaryKeyType &&id)
{
    RestfulUserPageCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulUserPageCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUserPageCtrlBase::get(req, std::move(callback));
}

void RestfulUserPageCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUserPageCtrlBase::create(req, std::move(callback));
}
