/**
 *
 *  RestfulPagesCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulPagesCtrlBase.h"

#include "Pages.h"
using namespace drogon;
using namespace drogon_model::task;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the pages table.
 */

class RestfulPagesCtrl: public drogon::HttpController<RestfulPagesCtrl>, public RestfulPagesCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulPagesCtrl::getOne,"/api/control/pages/{1}",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulPagesCtrl::updateOne,"/api/control/pages/{1}",Put,Options,"user::authorize");
    ADD_METHOD_TO(RestfulPagesCtrl::deleteOne,"/api/control/pages/{1}",Delete,Options,"user::authorize");
    ADD_METHOD_TO(RestfulPagesCtrl::get,"/api/control/pages",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulPagesCtrl::create,"/api/control/pages",Post,Options,"user::authorize");
    //ADD_METHOD_TO(RestfulPagesCtrl::update,"/api/control/pages",Put,Options,"user::authorize");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Pages::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Pages::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Pages::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
