/**
 *
 *  RestfulAnswersCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulAnswersCtrlBase.h"

#include "Answers.h"
using namespace drogon;
using namespace drogon_model::task;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the answers table.
 */

class RestfulAnswersCtrl: public drogon::HttpController<RestfulAnswersCtrl>, public RestfulAnswersCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulAnswersCtrl::getOne,"/api/control/answers/{1}",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulAnswersCtrl::updateOne,"/api/control/answers/{1}",Put,Options,"user::authorize");
    ADD_METHOD_TO(RestfulAnswersCtrl::deleteOne,"/api/control/answers/{1}",Delete,Options,"user::authorize");
    ADD_METHOD_TO(RestfulAnswersCtrl::get,"/api/control/answers",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulAnswersCtrl::create,"/api/control/answers",Post,Options,"user::authorize");
    //ADD_METHOD_TO(RestfulAnswersCtrl::update,"/api/control/answers",Put,Options,"user::authorize");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Answers::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Answers::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Answers::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
