/**
 *
 *  RestfulAnswersCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulAnswersCtrl.h"
#include <string>


void RestfulAnswersCtrl::getOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Answers::PrimaryKeyType &&id)
{
    RestfulAnswersCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulAnswersCtrl::updateOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Answers::PrimaryKeyType &&id)
{
    RestfulAnswersCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulAnswersCtrl::deleteOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Answers::PrimaryKeyType &&id)
{
    RestfulAnswersCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulAnswersCtrl::get(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulAnswersCtrlBase::get(req, std::move(callback));
}

void RestfulAnswersCtrl::create(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulAnswersCtrlBase::create(req, std::move(callback));
}
