/**
 *
 *  RestfulScorerQuestionCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulScorerQuestionCtrlBase.h"

#include "ScorerQuestion.h"
using namespace drogon;
using namespace drogon_model::task;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the scorer_question table.
 */

class RestfulScorerQuestionCtrl: public drogon::HttpController<RestfulScorerQuestionCtrl>, public RestfulScorerQuestionCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulScorerQuestionCtrl::getOne,"/api/control/scorerquestion/{1}",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulScorerQuestionCtrl::updateOne,"/api/control/scorerquestion/{1}",Put,Options,"user::authorize");
    ADD_METHOD_TO(RestfulScorerQuestionCtrl::deleteOne,"/api/control/scorerquestion/{1}",Delete,Options,"user::authorize");
    ADD_METHOD_TO(RestfulScorerQuestionCtrl::get,"/api/control/scorerquestion",Get,Options,"user::authorize");
    ADD_METHOD_TO(RestfulScorerQuestionCtrl::create,"/api/control/scorerquestion",Post,Options,"user::authorize");
    //ADD_METHOD_TO(RestfulScorerQuestionCtrl::update,"/api/control/scorerquestion",Put,Options,"user::authorize");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                ScorerQuestion::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   ScorerQuestion::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   ScorerQuestion::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
